export const SAVE_USER_INFO = "SAVE_USER_INFO";
export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN";
export const DELETE_USER = "DELETE_USER";
export const RESET_TIP = "RESET_TIP";

export const SELECT_LAN = "SELECT_LAN";

export const SAVE_SLOT_VENDORS = "SAVE_SLOT_VENDORS";

export const SAVE_ANNOUNCEMENTS = "SAVE_ANNOUNCEMENTS";
export const SAVE_ANNOUNCEMENTS_CATEGORIES = "SAVE_ANNOUNCEMENTS_CATEGORIES";
export const SELECT_ANNOUNCEMENTS_CATEGORY = "SELECT_ANNOUNCEMENTS_CATEGORY";
export const SWITCH_ANNOUNCEMENTS_MODAL = "SWITCH_ANNOUNCEMENTS_MODAL";
export const SWITCH_ANNOUNCEMENTS_POPUP = "SWITCH_ANNOUNCEMENTS_POPUP";